version: 2
jobs:
  build:
    working_directory: /dockerapp1
    docker:
      - image: iamalvis/mlops:latest
    steps:
      - checkout
      # - setup_remote_docker
      - run:
          name: Run tests
          command: pytest
      # - deploy:
      #     name: Push application Docker image
      #     command: |
      #       docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
      #       docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp1:$CIRCLE_SHA1
      #       docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp1:latest
      #       docker push $DOCKER_HUB_USER_ID/dockerapp1:$CIRCLE_SHA1
      #       docker push $DOCKER_HUB_USER_ID/dockerapp1:latest
